name: LR CMS Sync
on:
  workflow_dispatch: # 允许手动点击按钮触发
  push:
    paths:
      - 'sync_data.py'

# 增加下面这两行，赋予机器人写入仓库的权限（通行证）
permissions:
  contents: write

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Requests
        run: pip install requests
      - name: Run Sync
        run: python sync_data.py
      - name: Auto Commit
        run: |
          git config --global user.name "LR-Bot"
          git config --global user.email "bot@lyauw.me"
          git add data.json
          git commit -m "CMS Update: $(date)" || exit 0
          git push
